package com.sjianjun.reader.utils

import java.nio.charset.StandardCharsets
import java.security.MessageDigest

object NicknameGenerator {

    private val nicknames = """
        哀而不伤
        安然无恙
        安之若素
        白璧无瑕
        白驹过隙
        百川归海
        百读不厌
        百花齐放
        百炼成钢
        百折不挠
        彬彬有礼
        冰壶秋月
        冰清玉洁
        冰雪聪明
        博采众长
        博古通今
        博览群书
        博闻强识
        不卑不亢
        不同凡响
        不言而喻
        才高八斗
        才华横溢
        才思敏捷
        灿若繁星
        沧海遗珠
        姹紫嫣红
        长风破浪
        畅所欲言
        晨钟暮鼓
        成竹在胸
        驰名中外
        赤子之心
        崇山峻岭
        出类拔萃
        出奇制胜
        出神入化
        出水芙蓉
        楚楚动人
        川流不息
        春风得意
        春风化雨
        春华秋实
        春和景明
        春暖花开
        春山可望
        从容不迫
        从善如流
        璀璨夺目
        大器晚成
        大展宏图
        淡泊明志
        当仁不让
        德才兼备
        德高望重
        登峰造极
        滴水穿石
        点石成金
        砥砺前行
        地久天长
        顶天立地
        动人心弦
        独具慧眼
        独具匠心
        独树一帜
        独一无二
        多才多艺
        婀娜多姿
        耳聪目明
        发奋图强
        发人深省
        发扬光大
        繁花似锦
        返璞归真
        飞黄腾达
        丰神俊朗
        风华绝代
        风华正茂
        风调雨顺
        风姿绰约
        福寿安康
        高风亮节
        高歌猛进
        高山流水
        高瞻远瞩
        革故鼎新
        功成名就
        功德圆满
        光风霁月
        光明磊落
        鬼斧神工
        海晏河清
        海纳百川
        含英咀华
        浩气长存
        皓月千里
        鹤立鸡群
        鸿鹄之志
        后起之秀
        厚德载物
        湖光山色
        花好月圆
        花容月貌
        花团锦簇
        花香鸟语
        怀瑾握瑜
        欢天喜地
        焕然一新
        挥洒自如
        惠风和畅
        吉祥如意
        济济一堂
        家喻户晓
        嘉言懿行
        兼容并包
        见贤思齐
        见微知著
        匠心独运
        江山如画
        交相辉映
        脚踏实地
        教学相长
        金榜题名
        金碧辉煌
        金风玉露
        金科玉律
        金石为开
        金玉良言
        金玉满堂
        锦绣河山
        锦绣前程
        锦心绣口
        惊才绝艳
        惊鸿照影
        精诚所至
        精雕细琢
        精妙绝伦
        精卫填海
        精益求精
        敬业乐群
        九天揽月
        居安思危
        鞠躬尽瘁
        举案齐眉
        绝代风华
        君子之交
        开诚布公
        开卷有益
        慷慨激昂
        康庄大道
        可歌可泣
        刻画入微
        苦尽甘来
        苦心孤诣
        宽宏大量
        琅琅上口
        朗月清风
        乐善好施
        乐在其中
        雷厉风行
        礼尚往来
        励精图治
        良辰美景
        良师益友
        两全其美
        琳琅满目
        临风玉树
        另辟蹊径
        龙飞凤舞
        龙凤呈祥
        炉火纯青
        落落大方
        络绎不绝
        绿水青山
        满腹经纶
        茂林修竹
        美不胜收
        美轮美奂
        梦笔生花
        梦寐以求
        妙笔生花
        妙不可言
        妙趣横生
        名不虚传
        名列前茅
        名扬四海
        明察秋毫
        明德惟馨
        明眸皓齿
        莫逆之交
        难能可贵
        讷言敏行
        能工巧匠
        念念不忘
        宁静致远
        牛刀小试
        呕心沥血
        旁征博引
        蓬勃向上
        蓬荜生辉
        披沙拣金
        披星戴月
        平步青云
        平分秋色
        平易近人
        破釜沉舟
        七步成诗
        其乐融融
        气贯长虹
        气宇轩昂
        气壮山河
        千古绝唱
        千娇百媚
        千金一诺
        前程万里
        前程似锦
        巧夺天工
        巧思妙想
        锲而不舍
        琴瑟和鸣
        琴心剑魄
        勤能补拙
        青出于蓝
        青梅竹马
        青山绿水
        青云直上
        清风朗月
        清歌妙舞
        清新俊逸
        秋高气爽
        秋水长天
        秋水伊人
        全力以赴
        全神贯注
        群策群力
        群贤毕至
        人杰地灵
        人中龙凤
        仁心仁术
        忍辱负重
        日新月异
        容光焕发
        如虎添翼
        如花似锦
        如诗如画
        如沐春风
        如愿以偿
        锐不可当
        润物无声
        三生有幸
        三思而行
        三阳开泰
        山高水长
        山河锦绣
        山明水秀
        山清水秀
        赏心悦目
        诗情画意
        时来运转
        拾金不昧
        十全十美
        石破天惊
        世外桃源
        事半功倍
        手不释卷
        首屈一指
        书香门第
        书声琅琅
        熟能生巧
        疏影横斜
        水到渠成
        水木清华
        水天一色
        顺理成章
        岁寒三友
        岁月静好
        随遇而安
        所向披靡
        太平盛世
        谈笑风生
        韬光养晦
        桃李春风
        特立独行
        醍醐灌顶
        天保九如
        天高气清
        天光云影
        天朗气清
        天马行空
        天生丽质
        天衣无缝
        天真烂漫
        同甘共苦
        同舟共济
        投桃报李
        图南之志
        脱颖而出
        万里鹏程
        万象更新
        望穿秋水
        微言大义
        惟妙惟肖
        文从字顺
        文韬武略
        文武双全
        文质彬彬
        卧虎藏龙
        无价之宝
        无可比拟
        无微不至
        无懈可击
        无忧无虑
        无与伦比
        五彩缤纷
        五光十色
        五湖四海
        物华天宝
        物阜民丰
        洗尽铅华
        喜出望外
        细水长流
        鲜衣怒马
        闲情逸致
        弦歌不辍
        相得益彰
        相辅相成
        相敬如宾
        相濡以沫
        祥云瑞气
        逍遥自在
        小巧玲珑
        心安理得
        心驰神往
        心旷神怡
        心灵手巧
        心平气和
        心如止水
        心照不宣
        欣欣向荣
        星光璀璨
        星罗棋布
        行成于思
        行稳致远
        雄才大略
        雄姿英发
        秀外慧中
        旭日初升
        栩栩如生
        学富五车
        学贯中西
        学海无涯
        学无止境
        雪泥鸿爪
        雪月风花
        循序渐进
        言简意赅
        言之成理
        言之有物
        艳冠群芳
        扬长避短
        扬眉吐气
        阳春白雪
        洋洋大观
        养精蓄锐
        业精于勤
        一表人才
        一尘不染
        一帆风顺
        一飞冲天
        一见倾心
        一诺千金
        一片冰心
        一气呵成
        一日千里
        一如既往
        一丝不苟
        一往无前
        一叶知秋
        一语中的
        一枝独秀
        仪表堂堂
        仪态万方
        义薄云天
        逸趣横生
        意气风发
        饮水思源
        引人入胜
        英姿焕发
        莺歌燕舞
        有容乃大
        有声有色
        有始有终
        有条不紊
        有志竟成
        余音绕梁
        玉洁冰清
        玉立亭亭
        玉树临风
        郁郁葱葱
        月白风清
        月朗风清
        月朗星稀
        月明千里
        云蒸霞蔚
        云程发轫
        云淡风轻
        云开见月
        云水禅心
        运筹帷幄
        再接再厉
        载歌载舞
        战无不胜
        张弛有度
        张灯结彩
        掌上明珠
        朝气蓬勃
        朝乾夕惕
        真才实学
        真知灼见
        震古烁今
        蒸蒸日上
        正大光明
        正气凛然
        芝兰玉树
        芝兰生香
        枝繁叶茂
        知恩图报
        知书达礼
        知行合一
        栉风沐雨
        至善至美
        至真至纯
        掷地有声
        智圆行方
        智勇双全
        中流砥柱
        忠肝义胆
        众望所归
        珠联璧合
        珠圆玉润
        竹报平安
        专心致志
        壮志凌云
        卓尔不群
        自成一家
        自强不息
        自知之明
        足智多谋
        左右逢源
        紫气东来
    """.trimIndent()
        .lineSequence()
        .map { it.trim() }
        .filter { it.isNotEmpty() }
        .toList()

    init {
        check(nicknames.size >= 300) { "Nickname list must contain at least 300 entries." }
        check(nicknames.distinct().size == nicknames.size) { "Nickname list contains duplicates." }
    }

    fun generate(source: String?, fallback: String = "佚名"): String {
        val normalized = source?.trim()?.takeIf { it.isNotEmpty() } ?: return fallback
        val index = pickUniformIndex(normalized, nicknames.size)
        return nicknames[index] + normalized.take(2).uppercase()
    }

    private fun pickUniformIndex(source: String, bound: Int): Int {
        require(bound > 0) { "Bound must be greater than 0." }
        val range = 1L shl 32
        val acceptableUpperBound = range - (range % bound.toLong())
        var round = 0
        while (true) {
            val digest = sha256(if (round == 0) source else "$source#$round")
            var offset = 0
            while (offset + 4 <= digest.size) {
                val candidate = (((unsigned(digest[offset]) shl 24)
                        or (unsigned(digest[offset + 1]) shl 16)
                        or (unsigned(digest[offset + 2]) shl 8)
                        or unsigned(digest[offset + 3])).toLong()) and 0xFFFF_FFFFL
                if (candidate < acceptableUpperBound) {
                    return (candidate % bound.toLong()).toInt()
                }
                offset += 4
            }
            round++
        }
    }

    private fun sha256(text: String): ByteArray =
        MessageDigest.getInstance("SHA-256").digest(text.toByteArray(StandardCharsets.UTF_8))

    private fun unsigned(byte: Byte): Int = byte.toInt() and 0xFF
}

val String?.nickname: String
    get() = NicknameGenerator.generate(this)
